#!/bin/sh

MODDIR=/lib/modules

echo "[rcS] Init proton"
insmod $MODDIR/proton.ko

echo "[rcS] Init e2_proc"
insmod $MODDIR/e2_proc.ko

echo "[rcS] Init frontpanel"
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 3 min" > /dev/vfd
   echo "WAIT 3 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
else
   echo "Load 10" > /dev/vfd
fi

/etc/init.d/mountvirtfs start
var/etc/init.d/portmap start
var/etc/init.d/autofs start

echo "[rcS] Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

# Start automounter with umount timeout of 5 seconds
if [ -e $MODDIR/autofs4.ko ]; then
   insmod $MODDIR/autofs4.ko
fi
/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb

echo "[rcS] Starting telnetd"
/usr/sbin/telnetd -l /bin/autologin

echo "[rcS] Init stmfb (LOAD 9)"
echo "Load 9" > /dev/vfd
insmod $MODDIR/stmcore-display-stx7109c3.ko
insmod $MODDIR/stmfb.ko display0=720x576-32@60:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

echo "[rcS] Loading modules"

if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "NO FIRMW" > /dev/vfd
   sleep 5
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "Load 8" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096 2> /dev/null
/bin/ustslave /dev/st231-0 /lib/firmware/video.elf

echo "[rcS] Load audio firmware (LOAD 7)"
echo "Load 7" > /dev/vfd
/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096 2> /dev/null
/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf

echo "[rcS] Init embx (LOAD 6)"
echo "Load 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "Load 5" > /dev/vfd
insmod $MODDIR/avs.ko type=stv6418

echo "[rcS] Init player (LOAD 4)"
echo "Load 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
insmod $MODDIR/stmvout.ko
insmod $MODDIR/stmvbi.ko
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/fe-core.ko demod=stv090x tuner=stv6110x

insmod $MODDIR/cimax.ko
insmod $MODDIR/smartcard.ko
insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "Load 3" > /dev/vfd
insmod $MODDIR/player2.ko discardlateframe=0
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

stfbcontrol a 0

echo "[rcS] Init remote control (LOAD 2)"
echo "Load 2" > /dev/vfd
mkdir -p /var/run/lirc
/usr/bin/lircd
rm -rf /dev/rc
mknod /dev/rc c 147 1 
/bin/evremote2 10 120 &

echo "[rcS] Init smartcard cardreader"
mknod /dev/sci0 c 169 0
mknod /dev/sci1 c 169 1

stfbcontrol a 255

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "Load 1" >/dev/vfd
var/etc/init.d/vsftpd start
/usr/sbin/inetd

#timefix
date -s "201601011200"

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

echo "[rcS] Starting neutrino GUI ->"

until false
do
   /usr/local/bin/neutrino
   rtv=$?
   echo "GUI ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "$rtv"
              echo "RESTART"
              echo "Restart" > /dev/vfd
              ;;
      1) echo "$rtv"
              echo "SHUTDOWN"
              echo "Shutdown" > /dev/vfd
              init 0
              ;;
      2) echo "$rtv"
              echo "REBOOT"
              echo "Reboot" > /dev/vfd
              init 6
              ;;
      *) echo "*"
              echo -e "\033[01;31mERROR: $rtv\033[00m"
              echo "Error: $rtv" > /dev/vfd
              init 6
              ;;
   esac
done
